#+hugo_base_dir: .
* PapaSmurf.gg
:PROPERTIES:
:EXPORT_HUGO_SECTION: post
** Blog rants
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
Random thoughts and rants that have been created with org-mode and hugo

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: post
** DONE Call Sign Chaos
CLOSED: [2021-09-22 Wed 21:31]
:PROPERTIES:
:EXPORT_FILE_NAME: CallSignChaos
:EXPORT_DATE: 2021-09-19
:END:
#+begin_description
Call Sign Chaos: Learning to Lead by James N. Mattis, Bing West
#+end_description
*** Overview
Call Sign Chaos reflects on Jim Mattis's near 4 decades of experience in service to our country.  The book is divided into 3 parts: direct leadership, executive leadership, and strategic leadership. Jim Mattis recalls his lessons learned from Vietnam, Dessert Storm, Afghanistan, Iraq, NATO, Joint Forces Command, CENTCOM, and US Secretary of Defense.

Mattis's overarching themes of initiative, intent, and bias for action are throughout the book and insightful.
*** Quotes
I wanted to compile a list of quotes from this book that stood out to me, for my own reference in the future.
**** Direct Leadership
#+BEGIN_QUOTE
Woe to the unimaginative one who, in after-action reviews, takes refuge in doctrine. (XII)
#+END_QUOTE
#+BEGIN_QUOTE
From that wayward philosopher I learned that no matter what happened, I wasn't a victim; I made my own choices how to respond.  You don't always control your circumstances, but you can always control your response. (6)
#+END_QUOTE
#+BEGIN_QUOTE
I expected Andy to control the artillery fires. Nope. He left me alone to control the artillery, mortar, and machine guns as the troops advanced.  I had one mortar series plotted to land two hundred yards to the front of the troops.  I was sure the coordinates and timing were correct, so I spoke the code word and the shells slammed in.  The earth shook as a parallel sheaf of 81mm shells impacted the troops continued advancing.  Andy nodded and walked away.  I got the message: Have faith in your subordinates after you have trained them. (10)
#+END_QUOTE
#+BEGIN_QUOTE
Be brilliant in the basics.  Don't dabble in your job; you must master it. (11)
#+END_QUOTE
#+BEGIN_QUOTE
Show no favoritism. Value initiative and aggressiveness above all.  It's easier to pull the reins back than to push a timid soul forward. (12)
#+END_QUOTE
#+BEGIN_QUOTE
The Marine philosophy is to recruit for attitude and train for skills. Marines believe that attitude is a weapon system.  We searched for intangible character traits: a quest for adventure, a desire to serve with the elite, and the intention to be in top physical condition. (15)
#+END_QUOTE
#+BEGIN_QUOTE
I had learned in the fleet that in harmonious, effective units, everyone owns the unit mission.  If you as the commander define the mission as your responsibility, you have already failed.  It was our mission, never my mission. (16)
#+END_QUOTE
#+BEGIN_QUOTE
You don't control your subordinate commanders' every move; you clearly state your intent and unleash their initiative. (17)
#+END_QUOTE
#+BEGIN_QUOTE
Finally, I understood what President Eisenhower had passed on.  "I'll tell you what leadership is," he said.  "It's persuasion and conciliation and aducation and patience.  It's long, slow, tough work.  That's the only kind of leadership I know." (19)
#+END_QUOTE
#+BEGIN_QUOTE
Because a unit adopts the personality of its commander, just as a sports team adopts the personality of its coach, I made the expectation clear: I wanted a bias for action, and to bring out the initiative in all hands.  I would make do with what I had, and not waste time whining about what I didn't have. (21)
#+END_QUOTE
#+BEGIN_QUOTE
When you have to give up personnel, the tendency is to hang on to your best.  Nick's example stuck with me: When tasked with supporting other units, select those you most hate to give up.  Never advantage yourself at the expense of your comrades. (23)
#+END_QUOTE
#+BEGIN_QUOTE
Keeping me informed would be a lower priority. By listening over their tactical radio nets, I could gather information without interfering. But I needed more than that.  Using a technique I had found in my reading, I intended to gather informmation that bypassed normal reporting channels by means of "focused telescopes." (29)
#+END_QUOTE
#+BEGIN_QUOTE
Robert E. Lee says, "To be a good soldier you must love the army.  But to be a good officer you must be willing to order the death of the thing you love." (31)
#+END_QUOTE
#+BEGIN_QUOTE
By employing my focused telescopes and listening to the radio nets and my staff, I could keep abreast of events without calling a halt for meetings.  We were not slowing down.  I gave few orders, letting the assault leaders make the decisions. (34)
#+END_QUOTE
#+BEGIN_QUOTE
Before going into battle, you can learn by asking veterans about their experiences and by reading relentlessly. (42)
#+END_QUOTE
#+BEGIN_QUOTE
If you haven't read hundred's of books, you are functionally illiterate, and you will be incompetent, because your personal experiences alone aren't broad enough to sustain you.  Any commander who claims he is "too busy to read" is going to fill body bags with his troops as he learns the hard way. (42)
#+END_QUOTE
#+BEGIN_QUOTE
When you impose command via that sort of tight communications control, you create "Mother may I" timidity.  Once subordinate commanders sense that, they hesitate.  The very brittleness of detailed orders that cannot possibly anticipate unknowns sucks the initiative out of them, suffocating their aggressiveness and slowing operational tempo, a problem doubled if hobbled by risk aversion. (43)
#+END_QUOTE
#+BEGIN_QUOTE
When they make mistakes while doing their best to carry out your intent, stand by them.  Examine your coaching and how well you articulate your intent.  Remember the bottom line: imbue in them a strong bias for action. (45)
#+END_QUOTE
#+BEGIN_QUOTE
The Secretary of Defense most often had to choose the least bad option.  If it was an easy decision with good options, that decision had already been made. (49)
#+END_QUOTE
#+BEGIN_QUOTE
When a new boss brings in a large team of favorites, it invites discord and the concentration of authority at higher levels.  Using skip-echelon meant trusting subordinate commanders and staffs. (59)
#+END_QUOTE
#+BEGIN_QUOTE
Business management books often stress "centralized planning and decentralized execution."  That is too top-down for my taste.  I believe in centralized vision, coupled with decentralized planning and execution. (60)
#+END_QUOTE
#+BEGIN_QUOTE
Guided by robust feedback loops, I returned to three questions: What do I know? Who needs to know? Have I told them? (60)
#+END_QUOTE
**** Executive Leadership
#+BEGIN_QUOTE
I focused the divison on only two priorities: getting ready to deploy and how to fight under chemical attack.  I canceled all division-level inspections that did not pertain to those two tasks.  Attitudes are caught, not taught.  (81)
#+END_QUOTE
#+BEGIN_QUOTE
To win a dogfight, Boyd wrote, you have to observe what is going on, orient yourself, decide what to do, and act before your opponent has completed his version of the same process, repeating and repeating this loop faster than your foe. (90)
#+END_QUOTE
#+BEGIN_QUOTE
I took him aside--praise in public, criticize in private--before ripping into him.  I told him to get off his ass and do his job.  I had repeatedly emphasized speed--information passing, response to orders, movement, and resupply.  But leadership can't depend on emails or written words.  Leaders are not potted plants, and at all levels they must be constantly out at the critical points doing whatever is required to keep their teams energized, especially when everyone is exhausted. (103)
#+END_QUOTE
#+BEGIN_QUOTE
In formal circumstances, I'm calculating but I speak pointedly.  There's nothing to be gained by speaking obliquely about important matters. (132)
#+END_QUOTE
#+BEGIN_QUOTE
But whether you're a general or a CEO, win or lose, you have to fight a false narrative or it will assuredly be accepted as fact.  In the information age, you can't retreat to your office and let your public affairs officer take the tough questions. (140)
#+END_QUOTE
#+BEGIN_QUOTE
Regardless of rank or occupation, I believe that all leaders should be coaches at heart.  For me, "player-coach" aptly describes the role of a combat leader, or any real leader.
#+END_QUOTE
#+BEGIN_QUOTE
Commanders don't drive from the back seat.  Credit those below you with the same level of commitment and ability with which you credit yourself.  Make your intent clear, and then encourage your subordinates to employ a bias for action. (156).
#+END_QUOTE
#+BEGIN_QUOTE
There's a profound difference between a mistake and a lack of discipline.  Mistakes are made when you're trying to carry out a commander's intent and you screw up in the pressure of the moment. (166)
#+END_QUOTE
#+BEGIN_QUOTE
A leader must be willing to change and make change.  Senior staff sometimes need pruning.  It's easy to get into a bureaucratic rut where things are done a certain way because they're done a certain way.  That seems absurd when you read it in print--but it's the norm in large organizations.  Every few months, a leader has to step back and question what he and his organization are doing. (175).
#+END_QUOTE
#+BEGIN_QUOTE
Initiative has to be practiced daily, not stifled, if it's to become a reality inside a culture.  Every institution gets the behavior it rewards. (179)
#+END_QUOTE
#+BEGIN_QUOTE
The course of this effort was not easy, but any leader, whether a commander or a CEO, must guide his or her organization around the rocks and shoals.  I took JFCOM off the shoals of EBO and steered in what I determined was the right course.  If you don't do that as a leader, you're along for the ride; you're not steering the ship. (183)
#+END_QUOTE
**** Strategic Leadership
#+BEGIN_QUOTE
I was determined that CENTCOM would be an advocate, not an obstacle, in getting our warfighters what they needed in a speedy manner. (197)
#+END_QUOTE
#+BEGIN_QUOTE
A former boss, Navy Captain Dick Stratton, who was held in the Hanoi Hilton for 2,251 daysas a "prisoner at war," had taught me that a call from the field is not an interruption of daily routine; it's the reason for the daily routine. (198)
#+END_QUOTE
#+BEGIN_QUOTE
In keeping with George Washington's approach to leadership, I would listen, learn, and help, then lead. (202)
#+END_QUOTE
This book was written before President Biden had even won the democratic nomination.  There is no doubt in my mind, from his readings, that he would have not mentioned him by name if Mattis knew he were to be president.  He views the position so highly, that to undermine the sitting President is to undermine the country.  I find these quotes regarding Biden interesting, not in terms of leadership, but in terms of the recent developments with the withdrawal of Afghanistan.  Mattis goes on to say that windrawal from Iraq was both an eventual policy of both the left and right administrations (Bush and Obama).
#+BEGIN_QUOTE
Vice President Biden and his assistants listened politely.  But as we spoke, I sensed I was making no headway in convincing the administration officals not to support Maliki.  It was like talking to people who lived in wooden houses but saw no need for a fire department.  I saw that the die was already cast. (207)
#+END_QUOTE
#+BEGIN_QUOTE
I found him [Biden] an admirable and amiable man.  But he was past the point where he was willing to entertain a "good idea." He didn't want to hear more; he wanted our forces out of Iraq.  Whatever path led there fastest, he favored.  He exuded the confidence of a man whose mind was made up, perhaps even indifferent to considering the consequences were he judging the situation incorrectly. (207)
#+END_QUOTE
#+BEGIN_QUOTE
But in conditions of high uncertainty, you must develop alternatives that may or may not come into play: always keep an ace in the hole. (216)
#+END_QUOTE
#+BEGIN_QUOTE
At the same time, I championed the values America stands for, even when it made our partners uncomfortable.  If I wanted them to listen to me, I had to respect their dignity in public. But I'm known for blunt speaking, and I was very blunt--in private. Public humiliation does not change our friends' behavior or attitudes in a positive way. (227).
#+END_QUOTE
#+BEGIN_QUOTE
For me, direct leadership was all about preparing my troops to win in close-quarters combat.  When you go into battle, you enter a different world.  I set out to engrain in every grunt an aggressive spirit and confidence in winning. (235)
#+END_QUOTE
#+BEGIN_QUOTE
I learned then and I believe now that everyone needs a mentor or to be a mentor--and that no one needs a tyrant.  At the same time, there's no substitute for constant study to master one's craft.  Living in history builds your own shock absorber, because you'll learn that there are lots of old solutions to new problems. (237)
#+END_QUOTE
#+BEGIN_QUOTE
Intent is a formal statement in which the commander puts himself or herself on the line.  Intent must accomplish the mission, it has to be achievable, it must be clearly understood, and at the end of the day, it has to deliver what the unit was tasked with achieving. (238)
#+END_QUOTE
#+BEGIN_QUOTE
By conveying my intent in writing and in person, I was out to win their coequal "ownership" of the mission: it wasn't my mission; rather from private through general, it was out mission.  I stressed to my staff that we had to win only one battle: for the hearts and minds of our subordinates. (239)
#+END_QUOTE
#+BEGIN_QUOTE
We sometimes find that we've grown organizations with echelons that have outlived their value.  Allowing bad processes to stump good people is intolerable. (242)
#+END_QUOTE
#+BEGIN_QUOTE
While processes are boring to examine, leaders must know their own well enough that they can master them and not be mastered by them. (242)
#+END_QUOTE

** DONE Luscious Strawberry Glazed Cheesecake Supreme
CLOSED: [2022-07-27 Wed 19:59]
:PROPERTIES:
:EXPORT_FILE_NAME: StrawBerryCheeseCake
:EXPORT_DATE: 2022-07-27
:END:
#+begin_description
Luscious Strawberry Glazed Cheesecake Supreme
#+end_description
*** Ingredients
**** Crust Ingredients
- 1 cup flour
- 1/4 cup sugar
- 1 tsp grated lemon peel
- 1/4 tsp vanilla
- 1 slightly beaten egg yolk
- 1/2 cup butter
**** Filling Ingredients
- 3 well beaten eggs
- 2 8-ounce packages of cream cheese, softened
- 1 cup sugar
- 2 tsp vanilla
- 1/2 tsp almond extract
- 1/4 tsp salt
- 3 cups sour cream
**** Glaze Ingredients
- 2 cups of fresh strawberries
- 3/4 cup water
- 2 tbsp cornstarch
- 1/2 cup sugar
*** Directions
**** Crust Directions
1. Mix flour, sugar, lemon peel
2. Cut in butter until crumbly
3. Add 1 beaten egg yolk and 1/4 tsp vanilla, Mix Welland
4. Pat 1/3 of dough on bottom of 9" spring form pan with sides removed
5. Bake at 400 degrees for 8 mins
6. Cool
7. Pat remaining dough on sides
**** Filling Directions
1. Mix eggs, cream cheese, sugar, vanilla, almond extract, and salt
2. Beat til smooth
3. Blend in sour cream
4. Pour into crust
5. Bake at 375 degrees for almost 1 hour
6. Cool and chill for 4-5 hours
**** Glaze Directions
1. Crust 1 cup of strawberries
2. Add water and cook 2 mins
3. Sieve
4. Mix cornstarch with 1/2 cup sugar
5. Slowly stir in heat berry mixture
6. Bring to a boil, stirring constantly
7. Cook or stir til mixture is thick and clear
8. Cool to room temperature
9. Halve remaining strawberries and place atop cake
10. Pour glaze onto cake
11. Chill 2 hours
12. Enjoy!
